### ISSUE TITLE
High Resource Usage

### ISSUE THREAD

**Issue by AlexPads** [matcracker/BedcoreProtect#12]
### Issue description

- Expected result: For the plugin to not use 100% CPU usage on a Ryzen 3600 CPU @ 4.0Ghz
- Actual result: Uses 100%+ CPU when nothing seems to be going on.
### Steps to reproduce the issue
1. Put plugin in server
2. Start server
3. View CPU usage at 100% or MUCH higher than it used to be

### OS and versions
* BedcoreProtect: 0.5.2
* PocketMine-MP: 3.11.1
* PHP: 7.3
* Server OS: Ubuntu 1.18 (PHP inside Docker Container)
* Game version: PE/Win10

### Plugins
 - BedcoreProtect 

### Crashdump, backtrace or other files
 ![Screen Shot 12-23-19 at 12 33 AM](https://user-images.githubusercontent.com/37447608/71337953-b8465200-2502-11ea-8364-896808dec529.PNG)

#### Extra

Tested on:
CPU's:
- Ryzen 3600X @ 4.0Ghz
- AMD Phenom X4 @5.0Ghz (OverClocked)
- Intel Xeon-E 2136
- Intel i7-7700K
(I own WitherHosting and have alot of hardware)
Ram:
- Samsung DDR3 1666mhz 
- Micron DDR3 and DDR4 2600Mhz
- Gigabyte DDR4 3000Mhz ECC and non ECC

Included for reference to show they are not like 1 core garbage CPU or Ram setups I have not looked into the plugin but i would assume that it has something to do with a loop getting stuck. or a really rapid listener.

**Comment by matcracker** [comment]
I'm trying to Windows 10 but I can't reproduce the issue.
Do you change something in the configuration file?

**Comment by AlexPads** [comment]
Hello mat, 

This is a config file from one of our customers experiencing this issue with our your plugin.
It seems to be an issue that is only on Linux hosts i tried on Win10 and got no results but started up my Linux VM and got the same high CPU usage I also started it up on a Linux PC running Debian6 and got same High CPU.
```
# Plugin language
language: eng

# Database settings
database:
  # The database type. "sqlite" and "mysql" are supported.
  type: sqlite

  # Edit these settings only if you choose "sqlite".
  sqlite:
    # The file name of the database in the plugin data folder.
    # You can also put an absolute path here.
    file: bedcore_database.db
  # Edit these settings only if you choose "mysql".
  mysql:
    host: 127.0.0.1
    # Avoid using the "root" user for security reasons.
    username: root
    password: ""
    # The database name where plugin stores data.
    schema:
  # The maximum number of simultaneous SQL queries
  # Recommended: 1 for sqlite, 2 for MySQL. You may want to further increase this value if your MySQL connection is very slow.
  worker-limit: 1

# The timezone where you are located. This is necessary to correctly log the time of events.
# To find your timezone, check here: https://www.php.net/manual/en/timezones.php
timezone: "Europe/Lisbon"

# A list of worlds where the plugin can track logs
enabled-worlds: []

# If enabled, BedcoreProtect will check for updates when your server starts up.
# If an update is available, you'll be notified via your server console.
check-updates: true

# If no radius is specified in a rollback or restore, this value will be
# used as the radius. Set to "0" to disable automatically adding a radius.
default-radius: 10

# The maximum radius that can be used in a command. Set to "0" to disable.
# To run a rollback or restore without a radius, you can use "r:#global".
max-radius: 100

# If enabled, items taken from containers (etc) will be included in rollbacks.
rollback-items: true

# If enabled, entities, such as killed animals, will be included in rollbacks.
rollback-entities: true

# Logs blocks placed by players.
block-place: true

# Logs blocks broken by players.
block-break: true

# Logs blocks that break off of other blocks; for example, a sign or torch
# falling off of a dirt block that a player breaks.
natural-break: true

# Properly track block movement, such as sand or gravel falling.
block-movement: true

# Logs blocks that burn up in a fire.
block-burn: true

# Logs when a block naturally ignites, such as from fire spreading.
block-ignite: true

# Logs explosions, such as TNT and Creepers.
explosions: true

# Track when an entity changes a block, such as an Enderman destroying blocks. (NOT FULLY IMPLEMENTED IN POCKETMINE YET)
entity-change: true

# Logs killed entities, such as killed cows and enderman.
entity-kills: true

# Logs text on signs. If disabled, signs will be blank when rolled back.
sign-text: true

# Logs lava and water sources placed/removed by players who are using buckets.
buckets: true

# Logs natural tree leaves decay.
leaves-decay: true

# Logs tree growth. Trees are linked to the player who planted the sappling. (NOT IMPLEMENTED IN POCKETMINE YET)
tree-growth: true

# Logs mushroom growth. (NOT IMPLEMENTED IN POCKETMINE YET)
mushroom-growth: true

# Logs natural vine growth. (NOT IMPLEMENTED IN POCKETMINE YET)
vine-growth: true

# Logs water flow. If water destroys other blocks, such as torches,
# this allows it to be properly rolled back.
water-flow: true

# Logs lava flow. If lava destroys other blocks, such as torches,
# this allows it to be properly rolled back.
lava-flow: true

# Allows liquid to be properly tracked and linked to players.
# For example, if a player places water which flows and destroys torches,
# it can all be properly restored by rolling back that single player.
liquid-tracking: true

# Track item transactions, such as when a player takes items from a
# chest, furnace, or dispenser. Necessary for any item based rollbacks.
item-transactions: true

# Track player interactions, such as when a player opens a door, presses
# a button, or opens a chest. Player interactions can't be rolled back.
player-interactions: true

# Logs changes made via the plugin "BlockSniper" if it's in use on your server.
blocksniper-hook: false
```
